include ../../common/include.mk

all: 1-1_1-2_hello_world 1-3_temp_conv_heading 1-4_1-5_rev_temp_conv 1-6_check-EOF 1-7_value-EOF 1-8_count_blanks_tabs_nls 1-9_squeeze_spaces 1-10_replace_tabs_bkspace_bslash 1-12_one_word_per_line 1-13_horiz_histogram 1-13-1_vert_histogram 1-14_vert_freq_histogram 1-15_temp_conv_using_func

1-1_1-2_hello_world: 1-1_1-2_hello_world.c
	${CC} ${CFLAGS} 1-1_1-2_hello_world 1-1_1-2_hello_world.c

1-3_temp_conv_heading: 1-3_temp_conv_heading.c
	${CC} ${CFLAGS} 1-3_temp_conv_heading 1-3_temp_conv_heading.c

1-4_1-5_rev_temp_conv: 1-4_1-5_rev_temp_conv.c
	${CC} ${CFLAGS} 1-4_1-5_rev_temp_conv 1-4_1-5_rev_temp_conv.c

1-6_check-EOF: 1-6_check-EOF.c
	${CC} ${CFLAGS} 1-6_check-EOF 1-6_check-EOF.c

1-7_value-EOF: 1-7_value-EOF.c
	${CC} ${CFLAGS} 1-7_value-EOF 1-7_value-EOF.c

1-8_count_blanks_tabs_nls: 1-8_count_blanks_tabs_nls.c
	${CC} ${CFLAGS} 1-8_count_blanks_tabs_nls 1-8_count_blanks_tabs_nls.c

1-9_squeeze_spaces: 1-9_squeeze_spaces.c
	${CC} ${CFLAGS} 1-9_squeeze_spaces 1-9_squeeze_spaces.c

1-10_replace_tabs_bkspace_bslash: 1-10_replace_tabs_bkspace_bslash.c
	${CC} ${CFLAGS} 1-10_replace_tabs_bkspace_bslash 1-10_replace_tabs_bkspace_bslash.c

1-12_one_word_per_line: 1-12_one_word_per_line.c
	${CC} ${CFLAGS} 1-12_one_word_per_line 1-12_one_word_per_line.c

1-13_horiz_histogram: 1-13_horiz_histogram.c
	${CC} ${CFLAGS} 1-13_horiz_histogram 1-13_horiz_histogram.c

1-13-1_vert_histogram: 1-13-1_vert_histogram.c
	${CC} ${CFLAGS} 1-13-1_vert_histogram 1-13-1_vert_histogram.c

1-14_vert_freq_histogram: 1-14_vert_freq_histogram.c
	${CC} ${CFLAGS} 1-14_vert_freq_histogram 1-14_vert_freq_histogram.c

1-15_temp_conv_using_func: 1-15_temp_conv_using_func.c
	${CC} ${CFLAGS} 1-15_temp_conv_using_func 1-15_temp_conv_using_func.c

clean:
	${CLEAN_CMD} 1-1_1-2_hello_world
	${CLEAN_CMD} 1-3_temp_conv_heading
	${CLEAN_CMD} 1-4_1-5_rev_temp_conv
	${CLEAN_CMD} 1-6_check-EOF
	${CLEAN_CMD} 1-7_value-EOF
	${CLEAN_CMD} 1-8_count_blanks_tabs_nls
	${CLEAN_CMD} 1-9_squeeze_spaces
	${CLEAN_CMD} 1-10_replace_tabs_bkspace_bslash
	${CLEAN_CMD} 1-12_one_word_per_line
	${CLEAN_CMD} 1-13_horiz_histogram
	${CLEAN_CMD} 1-13-1_vert_histogram
	${CLEAN_CMD} 1-14_vert_freq_histogram
	${CLEAN_CMD} 1-15_temp_conv_using_func
