include ../../common/include.mk

all: cyclicshift onerupee sorted-matrix-find palindrome btree-bfs-array tokenizer string-permutations largestincrseq squeeze-spaces rev_singly_ll prime helloworld datatypesizes findinfiles

findinfiles:
	${CC} findinfiles.c ${CFLAGS} findinfiles

datatypesizes:
	${CC} datatypesizes.c ${CFLAGS} datatypesizes

cyclicshift:
	${CC} cyclicshift.c ${CFLAGS} cyclicshift
	
onerupee:
	${CC} onerupee.c ${CFLAGS} onerupee

sorted-matrix-find: sorted-matrix-find.c
	${CC} sorted-matrix-find.c ${CFLAGS} sorted-matrix-find

palindrome: palindrome.c
	${CC} palindrome.c ${CFLAGS} palindrome

btree-bfs-array: btree-bfs-array.c
	${CC} btree-bfs-array.c ${CFLAGS} btree-bfs-array

tokenizer: tokenizer.c
	${CC} tokenizer.c ${CFLAGS} tokenizer

string-permutations: string-permutations.c
	${CC} string-permutations.c ${CFLAGS} string-permutations

largestincrseq: largestincrseq.c
	${CC} largestincrseq.c ${CFLAGS} largestincrseq

squeeze-spaces: squeeze-spaces.c
	${CC} squeeze-spaces.c ${CFLAGS} squeeze-spaces

rev_singly_ll: rev_singly_ll.c
	${CC} rev_singly_ll.c ${CFLAGS} rev_singly_ll

prime: prime.c
	${CC} prime.c ${CFLAGS} prime

helloworld: helloworld.c
	${CC} helloworld.c ${CFLAGS} helloworld

clean:
	${CLEAN_CMD} findinfiles 
	${CLEAN_CMD} datatypesizes 
	${CLEAN_CMD} cyclicshift
	${CLEAN_CMD} onerupee
	${CLEAN_CMD} sorted-matrix-find
	${CLEAN_CMD} palindrome
	${CLEAN_CMD} btree-bfs-array 
	${CLEAN_CMD} tokenizer 
	${CLEAN_CMD} string-permutations 
	${CLEAN_CMD} largestincrseq 
	${CLEAN_CMD} squeeze-spaces
	${CLEAN_CMD} rev_singly_ll
	${CLEAN_CMD} prime
	${CLEAN_CMD} helloworld 
