include ../../common/include.mk

all: hoppity meepmeep

hoppity: hoppity.c
	${CC} hoppity.c ${CFLAGS} hoppity

meepmeep: meepmeep.c
	${CC} meepmeep.c ${CFLAGS} meepmeep

clean:
	${CLEAN_CMD} hoppity 
	${CLEAN_CMD} meepmeep 
